<a href="https://colab.research.google.com/github/danielvieira95/POSDSBD/blob/master/Aula_01_DataScience_e_Big_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

dados = {
    "produto": ["Motor A", "Motor B", "Motor A", "Motor C", "Motor B"],
    "producao": [100, 120, 110, 90, 130],
    "defeitos": [5, 12, 6, 3, 15],
    "temperatura": [70, 82, 73, 68, 85]
}

df = pd.DataFrame(dados)

In [ ]:
df.head()

   produto  producao  defeitos  temperatura
0  Motor A       100         5           70
1  Motor B       120        12           82
2  Motor A       110         6           73
3  Motor C        90         3           68
4  Motor B       130        15           85

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   produto      5 non-null      object
 1   producao     5 non-null      int64
 2   defeitos     5 non-null      int64
 3   temperatura  5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

         producao   defeitos  temperatura
count    5.000000   5.000000     5.000000
mean   110.000000   8.200000    75.600000
std     15.811388   5.069517     7.503333
min     90.000000   3.000000    68.000000
25%    100.000000   5.000000    70.000000
50%    110.000000   6.000000    73.000000
75%    120.000000  12.000000    82.000000
max    130.000000  15.000000    85.000000

In [ ]:
df["temperatura"]

0    70
1    82
2    73
3    68
4    85
Name: temperatura, dtype: int64

In [ ]:
df[["produto", "temperatura"]]

   produto  temperatura
0  Motor A           70
1  Motor B           82
2  Motor A           73
3  Motor C           68
4  Motor B           85

In [ ]:
df[df["temperatura"] > 75]

   produto  producao  defeitos  temperatura
1  Motor B       120        12           82
4  Motor B       130        15           85

In [ ]:
df[
    (df["temperatura"] > 75) &
    (df["defeitos"] > 10)
]

   produto  producao  defeitos  temperatura
1  Motor B       120        12           82
4  Motor B       130        15           85

In [ ]:
df.query("temperatura > 75")

   produto  producao  defeitos  temperatura
1  Motor B       120        12           82
4  Motor B       130        15           85

In [ ]:
df["temperatura"].mean()

np.float64(75.6)

In [ ]:
df["producao"].mean()

np.float64(110.0)

In [ ]:
df["temperatura"].max()

85

In [ ]:
df["temperatura"].min()

68

In [ ]:
df.sort_values(
    by="temperatura",
    ascending=False
)

   produto  producao  defeitos  temperatura
4  Motor B       130        15           85
1  Motor B       120        12           82
2  Motor A       110         6           73
0  Motor A       100         5           70
3  Motor C        90         3           68

In [ ]:
df.groupby("produto")["producao"].mean()

produto
Motor A    105.0
Motor B    125.0
Motor C     90.0
Name: producao, dtype: float64

In [ ]:
df.groupby("produto")["defeitos"].mean()

produto
Motor A     5.5
Motor B    13.5
Motor C     3.0
Name: defeitos, dtype: float64

In [ ]:
df.groupby("produto").agg({
    "producao": "mean",
    "defeitos": "sum",
    "temperatura": "mean"
})

         producao  defeitos  temperatura
produto
Motor A     105.0        11         71.5
Motor B     125.0        27         83.5
Motor C      90.0         3         68.0

In [ ]:
df["taxa_defeitos"] = (
    df["defeitos"] / df["producao"] * 100
)

In [ ]:
df[[
    "producao",
    "defeitos",
    "temperatura"
]].corr()

             producao  defeitos  temperatura
producao     1.000000  0.966863     0.969334
defeitos     0.966863  1.000000     0.995051
temperatura  0.969334  0.995051     1.000000